GET http://localhost:5127

###
GET http://localhost:5127/games

###
GET http://localhost:5127/games/2

###
POST http://localhost:5127/games
Content-Type: application/json

{
    "name": "EA Football 2026",
    "genreId": 5,
    "price": 29.9,
    "releaseDate": "2025-08-21"
}

###
PUT http://localhost:5127/games/2
Content-Type: application/json

{
    "name": "Astroboy II",
    "genreId": 3,
    "price": 49.9,
    "releaseDate": "2025-06-01"
}

###
DELETE http://localhost:5127/games/3

###
